name: ballistic-analysis
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy>=1.21.0
  - pandas>=1.3.0
  - scipy>=1.7.0
  - scikit-learn>=1.0.0
  - statsmodels>=0.12.0
  - sympy>=1.8.0
  - matplotlib>=3.4.0
  - seaborn>=0.11.0
  - plotly>=5.0.0
  - bokeh>=2.4.0
  - jupyter>=1.0.0
  - jupyterlab>=3.0.0
  - ipywidgets>=7.6.0
  - pytesseract>=0.3.8
  - opencv>=4.5.0
  - pillow>=8.3.0
  - pytest>=6.2.0
  - pytest-cov>=2.12.0
  - black>=21.0.0
  - flake8>=3.9.0
  - mypy>=0.910
  - sphinx>=4.0.0
  - sphinx_rtd_theme>=0.5.0
  - dvc>=2.5.0
  - python-dotenv>=0.19.0
  - pip
  - pip:
    - pdf2image>=1.16.0
    - PyMuPDF>=1.18.0
    - tabula-py>=2.3.0
    - camelot-py>=0.10.1
    - pybind11>=2.7.0
    - pre-commit>=2.15.0